[project]
channels = ["conda-forge", "bioconda"]
name = "CB_ONT"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.9"
osfclient = ">=0.0.5,<0.0.6"

[target.osx-arm64.dependencies]
python = "3.9.*"
seqkit = "==2.10.0"
chopper = ">=0.10.0,<0.11"

[target.linux-64.dependencies]
python = "3.9.*"
seqkit = "==2.10.0"
emu = "==3.5.1"
cutadapt = ">=5.0,<6"
chopper = ">=0.9.0,<0.10"
grepq = ">=1.4.8,<2"
r-optparse = ">=1.7.5,<2"
r-ggplot2 = ">=3.5.2,<4"
bioconductor-decipher = ">=2.30.0,<3"
picrust2 = "==2.6.2"
