[project]
channels = ["conda-forge", "bioconda"]
name = "CB_ONT"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.9"

[target.osx-arm64.dependencies]
python = "3.9.*"

[target.linux-64.dependencies]
python = "3.10.*"
seqkit = "==2.10.0"
emu = "==3.5.1"
cutadapt = ">=5.0,<6"
chopper = ">=0.9.0,<0.10"
